[all]
master-node-1 ansible_host=192.168.15.129 ansible_user=node1 is_master=true
master-node-2 ansible_host=192.168.15.130 ansible_user=node2 is_master=true
minion-node-1 ansible_host=192.168.15.131 ansible_user=node3 is_minion=true salt_minion_id=ubuntu-minion-01
