name: CI/CD Pipeline - Minimal Ansible Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  ansible-deploy:
    name: Trigger Local Ansible Playbook
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Runner sẽ dùng luôn Python và Ansible đã cài sẵn trên máy local của bạn
      - name: Execute Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini site.yml
